[project]
name = "backend"
version = "0.1.0"
description = "A FastAPI backend for the project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "ruff>=0.11.4",
    "uvicorn>=0.34.0",
]
